### PR TITLE
Feat: Improved cache handling

### PR DESCRIPTION
**Pull request by vHeemstra**
- Adds option `clearCache` - Clears the cache before processing
- Adds option `cacheDir` - Choose the directory to use for caching
  - `cacheDir` by default is under the package's root folder in `node_modules/.cache/vite-plugin-imagemin/<packageName>`
  - Relative `cacheDir` path will be relative to Vite's `<root>` dir
  - Absolute `cacheDir` path will be just that

#### TODO
- [ ] Add tests for cache functionality and options

### CODE REVIEW

**Comment by vHeemstra** [comment]
### Log preview when using cache

#### Performance
_Logs from `npm run playground:build`_

logs-using-cache

All blue marked items are taken from the cache. Evidently there's a huge time benefit using the cache.

#### Re-process errored files and re-evaluate skipped variants
Also note that errored/skipped files will re-process. Files that were skipped because of size are not. They are taken from the cache and re-evaluated for inclusion. If they are still larger, they will be removed from the output dir but kept in the cache (marked dimmed blue; see `animated-transparent-1.gif.webp` below).

#### Partial processing
When some of the output files are missing from the cache or have changed (for whatever reason), the cache feature can now handle partial processing for those variants alone. In this example I manually removed two files from the cache:

logs-using-cache-with-missing-files

**Comment by naranjamecanica** [comment]
LGTM 👍🏻 I've tested it in multiple production projects and it works great!

**Comment by naranjamecanica** [comment]
The cache key option is really nice so I can force a full optimisation when I change some compression settings.

**Comment by vHeemstra** [comment]
Awesome!

Yeah, it is somewhat impossible to serialize/stringify the `plugins` part of the options since those are instances of plugins. And so there's no other way to have compression configs included in the generated key. So I thought this was (at least for now) the best way to let people distinguish their caches when only changing non-serializable options.

Side note: some options (like `verbose` and `cache`) are ignored when hashing the cache key to avoid separate caches when the contents would be the same.

Side note 2: the cache entries are in a file named with the cache key, while all the actual files are just in one folder. As long as their contents stays the same between configs, they can still be re-used I think. If this turns out to have buggy behavior, we can revert to putting all cache entries and files in a subfolder with the key name.

**Comment by vHeemstra** [comment]
I will merge this with the main branch into version 1.1.3

Feel free to submit issues if you encounter them or PRs if you have improvements!

**Pull request merged**
