### PR TITLE
Feat: better cache handling without external modules

### PR DESCRIPTION
**Pull request by naranjamecanica**
I've took your [PR](https://github.com/vHeemstra/vite-plugin-imagemin/pull/10) and made a version without any external modules. For readability i've made a seperate `cache.ts` file which handles all the caching logic. Hope you can merge it! 👍🏻

### CODE REVIEW

**Comment by vHeemstra** [comment]
Good idea to separate it into its own file.

I'll have a better look soon.

Side note: When cache is used for a input file, we can't show/log the resulting output files and (size) improvements. I was thinking about a way to store this info/stats with the cache entry, so it can be read and used in the result log. Is that useful you think?

**Comment by naranjamecanica** [comment]
That's a nice idea about the stats, I can look into that to make a start.

One other thing I thought of that's not handled well right now is that if you change the compression settings the cache should also be discarded. I'll look into that later tonight of tomorrow!

**Comment by vHeemstra** [comment]
Great!

Yeah that's what I liked about the cache package you introduced. It uses a hash of a `JSON.stringify`d object of all the options as the file name to store the cache entries. This way, if the options change, it will look for a different file for the cache entries.

We might use a similar hash for the name of a subfolder? In this folder there will be the entries json as well as the copies of the output files. In this way, you could easily switch between configs and still have caching on all of those.

**Comment by vHeemstra** [comment]
I merged your changes into the `improve-cache-handling` branch, so we can work on it on that branch until it's ready to merge with main.

**Pull request merged**
